### ISSUE TITLE
Facility to allow custom title & additional message

### ISSUE THREAD

**Issue by neha-goel** [neha-goel/Facebook-Groups-Analytics#1]
1. A text area for the user to type some custom message which will be posted with the auto content which is posted on groups. 2) A text box for the title of the post. - via @tusharvjoshi

**Comment by tusharjoshi** [comment]
The layout of the items shall be as follows:

+---------------------------------------------------------------------------------------------+
|                                 Header coming from TextBox                                  |
+---------------------------------------------------------------------------------------------+
|                                        Automatic Content                                            |
+---------------------------------------------------------------------------------------------+
|                       Larger message coming from Text Area                           |
+---------------------------------------------------------------------------------------------+

The application shall provide placeholders for the user to type the Header and the Larger message, before posting the post to the group.

**Comment by neha-goel** [comment]
Done.

**Comment by tusharjoshi** [comment]
I tested it with my poetry group and it is working awesome.  Thanks for making this available today so I could post the stats exactly after one week.  Last week I posted stats using this app.

Thanks again I am loving it.  Will add some more suggestions for site as well as app soon.

**Comment by neha-goel** [comment]
Great. Thanks.
