### ISSUE TITLE
Adding hotlinks to Names and Posts mentions

### ISSUE THREAD

**Issue by tusharjoshi** [neha-goel/Facebook-Groups-Analytics#3]
Provide hotlinks to the names and mentioned posts in the messages posted by the application.  If the names of people can be added like how we do it using @ in facebook messages they will get referred automatically from the message.

The posts can have a link to the post so people can go and check that post from that link.

**Comment by neha-goel** [comment]
Currently I guess this is not allowed. That's why added one button 'Result to copy & update'. To tag the users copy & paste it on facebook.

**Comment by tusharjoshi** [comment]
The feature of 'Result to copy & update' works like a charm.  Thanks for it.

Currently Facebook allows only 10 Tags in one post, please provide a text box to type number of Tag to be added with default as 10 and keep all other names as untagged.  This week I had to remove the tags from all Names after the first 10 tags.
