### ISSUE TITLE
Ignore self comments of the person in max commented stat

### ISSUE THREAD

**Issue by tusharjoshi** [neha-goel/Facebook-Groups-Analytics#5]
When others comment on poems the person himself reply in comments saying thanks etc.  These comments shall not contribute for the count of total number of comments received by the poster.

Enhance the logic of calculation of maximum comments received to the post by ignoring comments by the same person

**Comment by neha-goel** [comment]
Done. You can check the same on demo site. After selecting 'Top Comment Receivers' an option to Ignore self comments will appear.
