### ISSUE TITLE
Setting to ignore posts below certain size or line 

### ISSUE THREAD

**Issue by tusharjoshi** [neha-goel/Facebook-Groups-Analytics#6]
There shall be a facility to ignore posts having only 2 or 3 lines in the Top Posters stat.

Provide a text box to receive a number of max lines to include the post in Top posters count.

+--------------+
|_________| # of lines post must contain to qualify for Top posters stat
+--------------+

The logic shall ignore all the empty lines to figure out the # of lines in a post.

**Comment by neha-goel** [comment]
Added option to include only those posts having more than specific lines. Limit on lines will not gonna work if someone make a long post but without a line break. So, added one more option to limit words. You can specify any of them according to need. Option will appear after selecting 'Top status updators'.
